version: '2.2'
services:
  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.8-java8
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 5070:5070
  datanode:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
    ports:
      - 5075:5075

  spark-master:
    image: bde2020/spark-master:2.1.0-hadoop2.8-hive-java8
    hostname: spark-master
    ports:
      - 8888:8080
      - 7077:7077
    env_file:
      - ./hadoop.env

  spark-worker:
    image: bde2020/spark-worker:2.1.0-hadoop2.8-hive-java8
    depends_on:
      spark-master:
        condition: service_healthy
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8081
    env_file:
      - ./hadoop.env

  hue:
    image: bde2020/hdfs-filebrowser:3.11
    ports:
      - 8088:8088
    environment:
      - NAMENODE_HOST=namenode
